//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class t_comment
    {
        public int id { get; set; }

        [Required]
        public int postid { get; set; }
        public string username { get; set; }

        [Required]
        [RegularExpression(".+@.+\\..+", ErrorMessage = "Please Enter Correct Email Address")]
        public string email { get; set; }

        [Required]
        public string comment { get; set; }
        public string date_time { get; set; }
    
        public virtual t_posts t_posts { get; set; }
    }
}
